In [19]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt
from pandas import Series, DataFrame
from pylab import rcParams
import sklearn
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix,roc_curve, roc_auc_score

In [44]:
df=pd.read_csv('C:/Users/hp/Music/iNeuron/titanic data/train.csv')

df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [45]:
df1 = df[['Survived','Name','Pclass','Sex','Age','SibSp','Parch','Fare']]

In [46]:
df1

Survived                                               Name  Pclass  \
0           0                            Braund, Mr. Owen Harris       3   
1           1  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2           1                             Heikkinen, Miss. Laina       3   
3           1       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4           0                           Allen, Mr. William Henry       3   
..        ...                                                ...     ...   
886         0                              Montvila, Rev. Juozas       2   
887         1                       Graham, Miss. Margaret Edith       1   
888         0           Johnston, Miss. Catherine Helen "Carrie"       3   
889         1                              Behr, Mr. Karl Howell       1   
890         0                                Dooley, Mr. Patrick       3   

        Sex   Age  SibSp  Parch     Fare  
0      male  22.0      1      0   7.2500  
1    female  38.0      1      0  71.2833  
2    female  26.0      0      0   7.9250  
3    female  35.0      1      0  53.1000  
4      male  35.0      0      0   8.0500  
..      ...   ...    ...    ...      ...  
886    male  27.0      0      0  13.0000  
887  female  19.0      0      0  30.0000  
888  female   NaN      1      2  23.4500  
889    male  26.0      0      0  30.0000  
890    male  32.0      0      0   7.7500  

[891 rows x 8 columns]

In [47]:
df1.describe()

Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [48]:
df1.isnull().sum()

Survived      0
Name          0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
dtype: int64

In [49]:
df1.Sex.unique()

array(['male', 'female'], dtype=object)

In [50]:
df1['Surname'] = df1.Name.str.split(',').str.get(0)
df1

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


Survived                                               Name  Pclass  \
0           0                            Braund, Mr. Owen Harris       3   
1           1  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2           1                             Heikkinen, Miss. Laina       3   
3           1       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4           0                           Allen, Mr. William Henry       3   
..        ...                                                ...     ...   
886         0                              Montvila, Rev. Juozas       2   
887         1                       Graham, Miss. Margaret Edith       1   
888         0           Johnston, Miss. Catherine Helen "Carrie"       3   
889         1                              Behr, Mr. Karl Howell       1   
890         0                                Dooley, Mr. Patrick       3   

        Sex   Age  SibSp  Parch     Fare    Surname  
0      male  22.0      1      0   7.2500     Braund  
1    female  38.0      1      0  71.2833    Cumings  
2    female  26.0      0      0   7.9250  Heikkinen  
3    female  35.0      1      0  53.1000   Futrelle  
4      male  35.0      0      0   8.0500      Allen  
..      ...   ...    ...    ...      ...        ...  
886    male  27.0      0      0  13.0000   Montvila  
887  female  19.0      0      0  30.0000     Graham  
888  female   NaN      1      2  23.4500   Johnston  
889    male  26.0      0      0  30.0000       Behr  
890    male  32.0      0      0   7.7500     Dooley  

[891 rows x 9 columns]

In [52]:
grp = df1.groupby(['Sex', 'Pclass'])
df1.Age = grp.Age.apply(lambda x: x.fillna(x.median()))
df1

C:\Users\hp\Anaconda3\lib\site-packages\pandas\core\generic.py:5208: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


Survived                                               Name  Pclass  \
0           0                            Braund, Mr. Owen Harris       3   
1           1  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2           1                             Heikkinen, Miss. Laina       3   
3           1       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4           0                           Allen, Mr. William Henry       3   
..        ...                                                ...     ...   
886         0                              Montvila, Rev. Juozas       2   
887         1                       Graham, Miss. Margaret Edith       1   
888         0           Johnston, Miss. Catherine Helen "Carrie"       3   
889         1                              Behr, Mr. Karl Howell       1   
890         0                                Dooley, Mr. Patrick       3   

        Sex   Age  SibSp  Parch     Fare    Surname  
0      male  22.0      1      0   7.2500     Braund  
1    female  38.0      1      0  71.2833    Cumings  
2    female  26.0      0      0   7.9250  Heikkinen  
3    female  35.0      1      0  53.1000   Futrelle  
4      male  35.0      0      0   8.0500      Allen  
..      ...   ...    ...    ...      ...        ...  
886    male  27.0      0      0  13.0000   Montvila  
887  female  19.0      0      0  30.0000     Graham  
888  female  21.5      1      2  23.4500   Johnston  
889    male  26.0      0      0  30.0000       Behr  
890    male  32.0      0      0   7.7500     Dooley  

[891 rows x 9 columns]

In [53]:
df1.isnull().sum()

Survived    0
Name        0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Surname     0
dtype: int64

In [54]:
display(df1.dtypes)

Survived      int64
Name         object
Pclass        int64
Sex          object
Age         float64
SibSp         int64
Parch         int64
Fare        float64
Surname      object
dtype: object

In [55]:
#df1[['Age']]=df1[['Age']].fillna(value=age_mean)
df1['Age'] = df1['Age'].astype(int)

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [56]:
display(df1.dtypes)

Survived      int64
Name         object
Pclass        int64
Sex          object
Age           int32
SibSp         int64
Parch         int64
Fare        float64
Surname      object
dtype: object

In [57]:
df1.isnull().sum()

Survived    0
Name        0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Surname     0
dtype: int64

In [58]:
#Categorical Sex column to numeric

from sklearn.preprocessing import LabelEncoder

number = LabelEncoder()
df1['Sex'] = number.fit_transform(df1['Sex'].astype('str'))
df1
# 1-male : 0-female

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


Survived                                               Name  Pclass  Sex  \
0           0                            Braund, Mr. Owen Harris       3    1   
1           1  Cumings, Mrs. John Bradley (Florence Briggs Th...       1    0   
2           1                             Heikkinen, Miss. Laina       3    0   
3           1       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1    0   
4           0                           Allen, Mr. William Henry       3    1   
..        ...                                                ...     ...  ...   
886         0                              Montvila, Rev. Juozas       2    1   
887         1                       Graham, Miss. Margaret Edith       1    0   
888         0           Johnston, Miss. Catherine Helen "Carrie"       3    0   
889         1                              Behr, Mr. Karl Howell       1    1   
890         0                                Dooley, Mr. Patrick       3    1   

     Age  SibSp  Parch     Fare    Surname  
0     22      1      0   7.2500     Braund  
1     38      1      0  71.2833    Cumings  
2     26      0      0   7.9250  Heikkinen  
3     35      1      0  53.1000   Futrelle  
4     35      0      0   8.0500      Allen  
..   ...    ...    ...      ...        ...  
886   27      0      0  13.0000   Montvila  
887   19      0      0  30.0000     Graham  
888   21      1      2  23.4500   Johnston  
889   26      0      0  30.0000       Behr  
890   32      0      0   7.7500     Dooley  

[891 rows x 9 columns]

In [18]:
print(df1.Pclass.unique())
print(df1.Sex.unique())
print(df1.Age.unique())
print(df1.SibSp.unique())
print(df1.Parch.unique())

[3 1 2]
[1 0]
[22 38 26 35 29 54  2 27 14  4 58 20 39 55 31 34 15 28  8 19 40 66 42 21
 18  3  7 49 65  5 11 45 17 32 16 25  0 30 33 23 24 46 59 71 37 47 70 12
  9 36 51 44  1 61 56 50 62 41 52 63 43 60 10 64 13 48 53 57 80  6 74]
[1 0 3 4 2 5 8]
[0 1 2 5 3 4 6]


In [59]:
y=df1[['Survived']]
X=df1.drop(df1[['Survived','Surname','Name']],axis=1)

In [60]:
print(X)
print(y)

     Pclass  Sex  Age  SibSp  Parch     Fare
0         3    1   22      1      0   7.2500
1         1    0   38      1      0  71.2833
2         3    0   26      0      0   7.9250
3         1    0   35      1      0  53.1000
4         3    1   35      0      0   8.0500
..      ...  ...  ...    ...    ...      ...
886       2    1   27      0      0  13.0000
887       1    0   19      0      0  30.0000
888       3    0   21      1      2  23.4500
889       1    1   26      0      0  30.0000
890       3    1   32      0      0   7.7500

[891 rows x 6 columns]
     Survived
0           0
1           1
2           1
3           1
4           0
..        ...
886         0
887         1
888         0
889         1
890         0

[891 rows x 1 columns]


In [61]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size = 0.25, random_state= 355)

In [62]:
clf = DecisionTreeClassifier()
clf.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [63]:
clf.score(x_test,y_test)

0.7399103139013453

In [17]:
scalar = StandardScaler()

x_transform = scalar.fit_transform(X)

In [18]:
x_train,x_test,y_train,y_test = train_test_split(x_transform,y,test_size = 0.25, random_state= 355)

In [19]:
clf = DecisionTreeClassifier()
clf.fit(x_train,y_train)
clf.score(x_test,y_test)

0.7174887892376681

In [64]:
grid_param = {
    'criterion': ['gini', 'entropy'],
    'max_depth' : range(2,32,1),
    'min_samples_leaf' : range(1,10,1),
    'min_samples_split': range(2,10,1),
    'splitter' : ['best', 'random']
    
}

In [65]:
grid_search = GridSearchCV(estimator=clf,
                     param_grid=grid_param,
                     cv=5,
                    n_jobs =-1)

In [66]:
grid_search.fit(x_train,y_train)

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=DecisionTreeClassifier(class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort=False, random_state=None,
                                              splitter='best'),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': range(2, 32),
                         'm

In [67]:
best_parameters = grid_search.best_params_
print(best_parameters)

{'criterion': 'gini', 'max_depth': 10, 'min_samples_leaf': 3, 'min_samples_split': 3, 'splitter': 'random'}


In [68]:
grid_search.best_score_

0.8308383233532934

In [69]:
clf = DecisionTreeClassifier(criterion = 'gini', max_depth =10, min_samples_leaf= 3, min_samples_split= 3, splitter ='random')
clf.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=10,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=3,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='random')

In [70]:
clf.score(x_test,y_test)

0.757847533632287

In [27]:
# let's save the model
import pickle

with open('C:/Users/hp/Music/iNeuron'+ '/DT_modelForPrediction.sav', 'wb') as f:
    pickle.dump(clf,f)
    
with open('C:/Users/hp/Music/iNeuron'+ '/DT_standardScalar.sav', 'wb') as f:
    pickle.dump(scalar,f)


In [41]:
clf.predict(np.array([[3,1,22.00,1,0,7.25]]))

array([0], dtype=int64)

In [40]:
import pickle

with open('C:/Users/hp/Music/iNeuron'+ '/DT_modelForPrediction.sav', 'wb') as f:
    pickle.dump(clf,f)