<a href="https://colab.research.google.com/github/mrinalkhalder10/mrinal_Assignments/blob/master/Numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY  Assignment**

**Problem Statement 1:** 

Write a **function** so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of **N - i - 1**.

HINT: Such a matrix with a geometric progression in each row is named for **Alexandre-Theophile Vandermonde**
 

In [1]:
import numpy as np

def func_vander_matrix(inputvec, N, increasing=False):
    import numpy as np
    if increasing:
        outputvec =np.array([x**(N-i-1) for x in inputvec for i in range(N)]).reshape(inputvec.size,N)
    elif not increasing:
        outputvec =np.array([x**(i) for x in inputvec for i in range(N)]).reshape(inputvec.size,N)
    return outputvec

**Result :-**

In [3]:
inputvec = np.array([1,2,3,4,5])
print("Decreasing order matrix : \n",func_vander_matrix(inputvec,3,False),end="\n\n\n")
print("Increasing order matrix : \n",func_vander_matrix(inputvec,3,True))

Decreasing order matrix : 
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]


Increasing order matrix : 
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]


**Problem Statement 2:**

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

**Question:** Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.



In [13]:
def moving_window(a,k):
    res = np.cumsum(a, dtype=int)
    res[k:] = res[k:] - res[:-k]
    n=len(a)
    seq_no=n-k+1
    print(res[k - 1:] / k,end="\n\n")
    print("moving average sequence value is : ",seq_no)

**Result:**

In [18]:
a=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
b=[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
moving_window(a,3)
print("\n\n\n")
moving_window(b,4)

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]

moving average sequence value is :  11




[25. 35. 45. 55. 65. 75. 85.]

moving average sequence value is :  7
